#!/bin/bash

export PATH=/usr/bin:/bin:"$PATH"

LIB_DIR=$(dirname "$0")
ROLLOUT_DIR=$(dirname "$LIB_DIR")

unset app_key
while getopts "k:hmclds" option; do #{{{
  case $option in
    k)
      app_key=$OPTARG
      ;;
  esac
done #}}}


echo "Rollout post compile script"

cat 1>&2 << end_of_error_msg
error: Rollout.io SDK version was not reconfigured, aborting...
Our guess is that you changed Rollout.io version in your podfile, but have not reconfigured it yet.
If this is correct, please run the following command:
    "$ROLLOUT_DIR"/install/configure_pod.sh -k $app_key

If our guess is incorrect or if the above didn't help, please contact us at support@rollout.io
end_of_error_msg

exit 4

